### ISSUE TITLE
client reconnection issues

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#352] opened 2020-03-13 00:34 UTC
Client reconnections when refreshing the browser is exhibiting some strange behavior. Could be related to https://github.com/colyseus/colyseus/issues/207 ? @endel 

code is in the https://github.com/virtualcommons/port-of-mars/tree/question-340 branch, more specifically in 

GameRoom: https://github.com/virtualcommons/port-of-mars/blob/question-340/server/src/rooms/game/index.ts

Client: https://github.com/virtualcommons/port-of-mars/blob/question-340/client/src/views/Game.vue

Here's what we've tried:

1. set up `allowReconnection` in the game room with a timeout of 60s
2. kept the roomID and sessionID in local storage and invoke `client.reconnect(..)` with those credentials

Things we're encountering:

1. sometimes it connects to a different room entirely (new room ID)
2. sometimes we get a session expired error on the client
3. sometimes we get a seat reservation error on the client

additional context in #340

**Comment by endel** [comment] 2020-03-14 11:13
Hi @alee, this sounds strange.

> 1. sometimes it connects to a different room entirely (new room ID)

This should never happen when using `.reconnect()`. The only error that could happen when trying to reconnect with invalid arguments is `"session expired"`.

> 2. sometimes we get a session expired error on the client

This looks ok if the timeout of 60s has passed since the client left the room.

Would you mind upgrading both server-side and client-side to latest versions? I see you're still 
 using 0.11, there's a new option on [0.12.3](https://github.com/colyseus/colyseus/releases/tag/0.12.3) that allows you to reject the reconnection manually. So you could reject the reconnection only when the game has finished, for example. (instead of forcing for 60s)

The second block of code in the `allowReconnection()` section describes how to manually reject the reconnections: https://docs.colyseus.io/server/room/#allowreconnection-client-seconds

Hope this helps, please let me know if that doesn't work for you!

**Comment by alee** [comment] 2020-03-16 05:36
Doh - we'd assumed that we were running 0.12.x, I didn't realize that NPM semver versioning [doesn't upgrade 0.x.y minor versions with caret ranges](https://www.npmjs.com/package/semver#caret-ranges-123-025-004). 

The upgrade seems to have fixed nearly all the issues, thanks! Now the 1st refresh always works but I'm still getting a session expired on the second (and subsequent) refreshes no matter what we set as the timeout (refreshing well within the 60s, or if I leave the timeout out entirely). 

Is it OK if we ignore the consented boolean as well?

Thanks for the pointers, and hope you're staying safe + healthy! 😷

**Comment by endel** [comment] 2020-03-16 21:20
Hi @alee, glad upgrading has fixed!

> Is it OK if we ignore the consented boolean as well?

It should be fine! I've just added an example of `allowReconnection()` / `reconnect()` in the examples repository here: 
- https://github.com/colyseus/colyseus-examples/blob/master/rooms/04-reconnection.ts
- https://github.com/colyseus/colyseus-examples/blob/master/static/04-reconnection.html#L34

I could not reproduce the `"session expired"` you're having though, I imagine it may be due to other circumstances? If you happen to be able to reproduce using the minimal example in the `colyseus-examples` repository, I'll really appreciate it!

> hope you're staying safe + healthy! 😷

Thanks! I hope you and everyone in your University are safe too! Cheers!

**Comment by alee** [comment] 2020-03-20 01:01
hi @endel! I checked out the colyseus-examples locally and am getting the same result (the herokuapp at https://colyseus-examples.herokuapp.com/04-reconnection.html seems to have the same issue as well):

![session-expired](https://user-images.githubusercontent.com/22534/77127954-9b3ef380-6a0b-11ea-8601-ec8620c579c7.png)

This is using the latest version of chromium Version 80.0.3987.87 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by endel** [comment] 2020-03-20 12:08
Hi @alee, I see in the logs that `session expired` is being displayed before `"Bye bye"`, have you tried to "reconnect" before actually closing the connection? 👀

**Comment by alee** [comment] 2020-03-20 16:40
ahah, that's exactly right. So perhaps this is related to the issue we are running into in our app.. In our case, we are auto-joining the room as the page loads, then when we refresh we try to auto-join again. It's a bit of a mess at the moment, and I'm trying to dig through why our app is failing to reinitialize properly on refresh / reconnection.

**Comment by alee** [comment] 2020-03-26 06:50
Hi @endel hope all is well! I just got some more time to dig into this. So we can reconnect successfully within the `onLeave` function but after that is completed, subsequent requests to the room fail handled by `onMessage` fail because `client.auth` is no longer set available.. I'm not sure why that property disappears, as it is still present during `onLeave`. 

I'll try to see if I can create a reproducible minimal example in colyseus-examples but wanted to see if that flags any immediate issues that we might be doing wrong..

**Comment by endel** [comment] 2020-03-26 12:44
Hi @alee , glad the reconnection is working now! You're right about the `client.auth` issue. I've just released `colyseus@0.12.4` fixing this. Cheers!

**Comment by alee** [comment] 2020-03-26 15:00
works like a charm now, thanks for the fast response @endel!

**Closed** 2020-03-26 20:10 UTC
